services:
  - type: web
    name: tabpy-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "tabpy --config tabpy.conf --disable-auth-warning"
    autoDeploy: true
